services:
    backend:
        build: ./backend
        ports:
            - '8001:8001'
        volumes:
            - ./backend/app:/app/app
        environment:
            WATCHFILES_FORCE_POLLING: 'true'

    frontend:
        build: ./frontend
        ports:
            - '3001:3001'
        environment:
            # Used by the frontend to call the backend from the browser
            NEXT_PUBLIC_API_URL: 'http://localhost:8001'
            # Enable reliable file watching inside Docker on macOS/Windows
            WATCHPACK_POLLING: 'true'
            CHOKIDAR_USEPOLLING: 'true'
        volumes:
            - ./frontend:/app
            # Keep container's node_modules (from image) instead of host's
            - /app/node_modules
        depends_on:
            - backend
