services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    environment:
      # Used by the frontend to call the backend from the browser
      NEXT_PUBLIC_API_URL: "http://localhost:8000"
    depends_on:
      - backend
