from fastapi import FastAPI
from fastapi.middleware.cors import CORSMiddleware

app = FastAPI(
    title="Supermaker Backend",
    description="Backend API for autogenerated enterprise apps",
    version="0.0.1",
)

# CORS – adjust as needed
app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],   # lock this down later
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)

@app.get("/ping")
def ping():
    return {"message": "Pinging backend..."}